#spring:
#    datasource:
#        druid:
#            db-type: mysql
#            driver-class-name: com.mysql.cj.jdbc.Driver
#            url: jdbc:mysql://127.0.0.1:3306/testspring?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
#            username: root
#            password: 123456
#            initial-size: 5
#            min-idle: 5
#            max-active: 20
#            max-wait: 60000
#            web-stat-filter:
#                enabled: false
#            stat-view-servlet:
#                enabled: false
#        type: com.alibaba.druid.pool.DruidDataSource
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/testspring?characterEncoding=utf-8&serverTimezone=GMT%2B8&allowMultiQueries=true
        username: root
        password: 123456
    http:
        multipart:
            enabled: true
            max-file-size: 20MB
            max-request-size: 100MB
    task:
        excution:
            pool:
                core-size: 5
                max-size: 10
server:
    port: 8081
    tomcat:
        uri-encoding: utf-8
        max-connections: 2000
        max-threads:  2000
mybatis:
    configuration:
        mapUnderscoreToCamelCase: true
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    mapper-locations: classpath*:mapper/*.xml,classpath*:dao/ceadao/*.xml
